include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    unnecessary_ignore: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
    avoid_catches_without_on_clauses: ignore
linter:
  rules:
    public_member_api_docs: false